---
- hosts: all
  sudo: yes
  tasks:
    - name: install apache2
      apt: name=apache2 update_cache=yes state=latest

    - name: enabled mod_rewrite
      apache2_module: name=rewrite state=present
    - name: Clone a private repository into /opt.
      git:
        repo: https://github.com/rameshkalluri/Test.git
        version: master
        dest: /var/www/html/
        accept_hostkey: yes
  # ssh-agent doesn't allow key to pass through remote sudo commands.
        become: no
~

