- hosts: all
  gather_facts: False
  vars:
    - packages: ["git", "openssl","docker","docker-compose"]
  tasks:
    - name: Installing {{ packages }} on {{ hostname }}
      yum:
        name: "{{ item }}"
        state: present
      with_items: "{{ packages }}"
